spring.application.name=springboot

spring.datasource.url=jdbc:postgresql://localhost:5432/prodructs_api
spring.datasource.username=postgres
spring.datasource.password=peixegamer123
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true